### PR TITLE
Added mjId2015 to jetSelBits in MiniAOD.

### PR DESCRIPTION
**Pull request by dabercro**

### CODE REVIEW

**Comment by amarini** [comment]
#173

**Comment by dabercro** [comment]
Hang on, sorry. Sid pointed out that the Id is a little more complicated. Let me check the twiki.

**Comment by amarini** [comment]
What is the status ?

**Comment by dabercro** [comment]
I think the ID should be filling properly now.

**Comment by sidnarayanan** [comment]
@dabercro Can you add the same code to NeroPuppiJets? The ID is the same and is filled in the same way.

**Comment by dabercro** [comment]
Okay, I added those. I think you guys are asking for trouble maintaining copies of the same code though.

**Comment by amarini** [comment]
@sidnarayanan, this should avoid code duplication. At the moment all the id are identical to the normal jets, if I am correct, and in future we still be able to add ad hoc stuff for puppi.

**Pull request merged**
