### PR TITLE
MC particle, fatjet, and puppi updates

### PR DESCRIPTION
**Pull request by sidnarayanan**
MINIAOD changes:

- Re-enabled ability to cluster puppi and fatjets

- doReclustering turns off all puppi and fatjets

- Added doAK8, doCA15, doPuppi for additional customization

- Added filler for gen particle parent information. Noticed that many copies of pruned gen particles are saved. Can be improved

Bambu changes:

- Fatjets and puppi MET now updated for 043+. Reclustering no longer necessary

- Added filler for gen particle parent information

### CODE REVIEW

**Comment by sidnarayanan** [comment]
I can add the fix referenced in #209 to this PR

**Comment by amarini** [comment]
Yes add that fix, please.
Can you also comment this block (metSystPuppi shifts):
https://github.com/MiT-HEP/NeroProducer/blob/master/Nero/src/NeroMet.cpp#L116-L121
I guess that since the puppi recepe in miniaod is ~wrong, nobody will use it out of the box, and this may use a lot of resources. (14 float x event).

Can you also uncomment in this block? Dima was interested in the trk met, 
so we will have it in the next iteration:
https://github.com/MiT-HEP/NeroProducer/blob/master/Nero/src/NeroMet.cpp#L58-L78

**Comment by sidnarayanan** [comment]
Summary of additional changes:

- Only save pruned gen particles if there is not a mother of the same PDG ID. 

- Removed PUPPI MET systematics

- Added Trk MET

**Comment by sidnarayanan** [comment]
@yiiyama @amarini 

Give me another day to review the Bambu fixes. I want to double-check some things for mono-V are still working.

**Comment by sidnarayanan** [comment]
@yiiyama I have made it so that the Bambu filler can accept fat jets stored in Bambu or produced from FatJetExtender. The default is to use the latter option for AK8 CHS and the former for everything else.

**Comment by sidnarayanan** [comment]
Given what is being seen in the W/Z analysis, I have written our own PUPPI recipe to bypass what is in MINIAOD. The custom configuration is in Nero/python/Puppi_cff.py. The custom recipe is used only if doReclustering and doPuppi are both turned on. 

NeroMet now can handle both pat::METCollection and reco::PFMETCollection. I think NeroMetRecluster is therefore redundant and can be removed.

I also added Fall15_25nsV2 JEC files.

**Pull request merged**
