### PR TITLE
76X

### PR DESCRIPTION
**Pull request by amarini**
* upgrading to 76. 
* Switching to in release HBB. 
* Start Removal of MetNoHF

Todo:
* Global Tag
* align all the cfg.py

### CODE REVIEW

**Comment by drkovalskyi** [comment]
What are plans for 74X?

Dima

**Comment by amarini** [comment]
I don't think we have a plan nor for 76X nor for 74X. 
It is likely we will discuss it in Jan, when we will figure out what will happen.

The idea is to be ready for the rereco. If we want to maintain a 74X and a 76X we need to have available the miniAOD in the releases we want to use (in order to have the content and the header aligned).  For the moment I tried to run on some MC already processed, 
and luckily there are not huge differences.

It is likely that, unless there are major bug in the rereco, everybody is going to move to it for Moriond.
I will not merge this PR until we have data rereco (mid Jan), global tag ... 

Andrea

**Comment by drkovalskyi** [comment]
So the master will stay 74X till we are ready to move to 76X? When we do it, can we keep a branch for 74X just in case?

Dima

**Comment by amarini** [comment]
I re-align the changes for 76X on top of the current developments. We need to use >= 763p2 because otherwise we are not able to read the JEC files.

**Comment by amarini** [comment]
If no objection, Monday I'll branch the 74X and merge this into the master (that will become 76X).

**Pull request merged**
