### PR TITLE
photon id. 

### PR DESCRIPTION
**Pull request by amarini**
There is a double somersault to make it work with the met/puppi recipe.
If the variable definition (like sieie/r9 ...)  do not change this should work.

### CODE REVIEW

**Comment by amarini** [comment]
@zdemirag

**Comment by zdemirag** [comment]
This seems to be only update on the id / merge branches. There are other corrections to be applied on top of the EGMSmearer corrections, which are residual scale corrections are to be applied on data only for BARREL only in bins of energy of the seed crystal

details here: https://twiki.cern.ch/twiki/bin/view/CMS/EGMSmearer

**Comment by amarini** [comment]
Testing it right now.

**Comment by zdemirag** [comment]
For the puppi crash in run time we will have to add to our config:

process.puppiForMET.photonId = cms.InputTag("egmPhotonIDs","cutBasedPhotonID-Spring15-25ns-V1-standalone-loose")

instead of the "cutBasedPhotonID-Spring15-25ns-V1-standalone-loose" whatever the new loose id is.

I have informed the puppi group to update their recipes from Jet/MET side

**Comment by amarini** [comment]
I'm testing it right now, I will use the loose Photon Id definition we use in the ntuples.
The other part of the recipe includes as well the fixes propagated to the twiki page today.

**Comment by amarini** [comment]
No, this way is not gonna work. 
We can't use their modulo (calibratedPatWhatever) because the met would be wrong.
I'm reimplementing it inline as it was, I will not propagate any changes (needs to be done offline) but save the correction.

**Comment by amarini** [comment]
And it is also a deterministic smearing. 
The only draw back is that scale and smear applied here are done after E/p combination, instead of before, but in this way we can propagate any changes to the met (rather than having it unphysical)

**Comment by zdemirag** [comment]
I am not sure why you think this is not gonna work for met? In puppi met, the photon id is only used to determine which photon should be considered in the puppi photon collection.

Or are you referring to something else when you say this is not gonna work?

**Comment by amarini** [comment]
No, @zdemirag is an other thing.
Met is the negative sum of whatever you have in the event.
If you do it with PF objects have some value. If you correct electrons/photons, you need to propagate your correction to the met (as you do for JEC).

**Comment by zdemirag** [comment]
ok, and yes of course (about the met comment). The issue is not as simple, like in the jet case for MET, but on the MET POG side i'll make sure to investigate. Of course has no implications in our tuple producer, so I was confused about your comment. thanks for clarifying :)

**Comment by amarini** [comment]
But this is why I'm saving the correction factors, separatly to be applied offline. (btw they are deterministic since the seed is using a function of r/l/e). So we can have a physically consistent description of the event. (MET and EG)

**Comment by zdemirag** [comment]
Fair enough, this would work. We just need to make sure we do it consistently for electrons / photons. Thank you.

**Pull request merged**
