### PR TITLE
Added photon branches needed for monophoton analysis.

### PR DESCRIPTION
**Pull request by blallen**
Most of this was just adding additional variables to the extended section. However, I also had to add some additional Electron Vetos to the ID enum, so values for the non-POG IDs changed.

### CODE REVIEW

**Comment by amarini** [comment]
Is this for 74X? You may want to port something to 76X before we branch the 80X.

**Comment by yiiyama** [comment]
I'll take care of porting.

**Comment by yiiyama** [comment]
Actually, electron veto bits need correction. PhoElectronVeto that already existed is the conversion safe veto, so we don't need a new CSafeVetoBit. Brandon, can you make an update?

**Comment by yiiyama** [comment]
And we should make things backward-compatible where possible - I'd say we can keep the existing bits as is, and have the PixelSeedVeto as a "non-POG" bit, after TightNoEVeto.

**Comment by blallen** [comment]
Okay, I spoke with Andrea and he said that he's not using the photons currently so it's okay if we break backwards compatibility. What I did ended up doing was dropping the extra ElectronVeto bit and then starting the enum for the non-POG IDs at 100. That should give us enough room for any future changes.

As far as I know Github is supposed to automatically update the PR if you add commits to the branch it was from... but this isn't happening. Do I have to make a new PR because this one was merged?

**Comment by amarini** [comment]
Be carefull that the unsigned should have 32 bits "only" and the Long 64.

**Comment by blallen** [comment]
Okay, changed to instead start non-POG IDs at 16. So half for POG and half for non-POG.

**Pull request merged**
