### PR TITLE
Remove JER

### PR DESCRIPTION
**Pull request by amarini**
#235

### CODE REVIEW

**Comment by amarini** [comment]
#234

**Comment by amarini** [comment]
Adding SC Eta to Photons and Electrons. 
Removing is25ns/is50ns/is2016 ... everywhere (this will be used for the time being only for 2016).

**Comment by amarini** [comment]
@zdemirag, @blallen with this configuration, met and photons seems ok for MC and DATA.
I just look a ~100s of entries, so a more precise data/mc comparison is needed.
I don't know if the egamma vid has a more updated version rather than v1 25ns.

**Comment by amarini** [comment]
@zdemirag, after this PR the track met is correctly working. 
Be aware that scan of a tlorentzVector gives 0, so you need to ask for eg Pt.

root [4] events->Scan("trackMet:trackMet.Pt():trackMet.Eta():trackMet.Phi()")
************************************************************
*    Row   *  trackMet * trackMet. * trackMet. * trackMet. *
************************************************************
*        0 *         0 * 29.620964 * 1.7763717 * -1.624882 *
*        1 *         0 * 59.767745 * -2.346239 * -1.490831 *
*        2 *         0 * 13.445789 * -2.849428 * 2.7993512 *
*        3 *         0 * 18.569416 * -0.309454 * -2.398665 *
*        4 *         0 * 28.050052 * 3.0297633 * 2.6165404 *
*        5 *         0 * 84.023004 * -1.902530 * -2.583610 *

**Comment by zdemirag** [comment]
Thank you will take a look asap

**Pull request merged**
