### PR TITLE
Bambu v0004

### PR DESCRIPTION
**Pull request by yiiyama**
. PuppiJets
. GenJet no neutrinos
. Met sumEt
. Photon high-pt id
. Many more lepton ids
. PDF & QCD scale reweighting
. etc etc

### CODE REVIEW

**Comment by yiiyama** [comment]
@amarini There are some changes to Core. Please take a look.

**Comment by amarini** [comment]
We will merge this before a big production to preserve the back compatibility of the reader as much as possible.

**Comment by amarini** [comment]
can you point to the how to get the weights for the specific pdf, so we try to keep these aligned.
(for the scale r2f1 ... I implemnted it )

**Comment by yiiyama** [comment]
We have a pdf reweight configuration tag for each dataset in [Bambu/config/datasets.list](https://github.com/MiT-HEP/NeroProducer/blob/master/Bambu/config/datasets.list). The second last column is the tag: - for data or MC datasets that do not have PDF reweight info, `amc_74` for aMC@NLO samples, `mg5_74` for MG5 LO samples, and `pwhg_74` for POWHEG samples (fortunately, so far the generator team have been using a fixed PDF configuration for each generator). Then in the [ntuples production](https://github.com/MiT-HEP/NeroProducer/blob/master/Bambu/config/datasets.list), this tag is resolved to either reweight factor group names or ids. In the [MonteCarloFiller](https://github.com/MiT-HEP/NeroProducer/blob/master/Bambu/source/MonteCarloFiller.cc#L22), the LHE header info is unpacked to extract the reweight ids in the reweight factor groups, and then finally in each event the reweight factor is obtained using these ids.

An example code for fetching the reweight ids, definitions, group names, etc. is here:
Deal with LHERunInfo: https://github.com/cpausmit/MitProd/blob/master/TreeFiller/src/FillerMCEventInfo.cc#L261
Deal with LHEEventInfo: https://github.com/cpausmit/MitProd/blob/master/TreeFiller/src/FillerMCEventInfo.cc#L150

**Pull request merged**
