### PR TITLE
switching lepton id branch from signed to unsigned

### PR DESCRIPTION
**Pull request by yiiyama**
As long as the lepTightId variable is used as a pure bitmask, or as long as we only utilize the first 31 bits, whether it's an int or an unsigned does not matter. This is more about aesthetics, I guess. Have tested reading a file produced with the previous branch definition and saw no problem.

### CODE REVIEW

**Comment by drkovalskyi** [comment]
I would also change the name. It's not tight id. It's lepton selection requirements. If people already use it heavily we can keep the tightId and introduce a proper lepton selection bitmap. (it's not just id, it may also include isolation, basically it's a full selection of some type). I would deprecate the old one and remove at some point.

**Comment by amarini** [comment]
I agree, tightID would be misleading.

**Comment by amarini** [comment]
can you check the error in running  (just remove the double dot in the details link) ?
I guess that we need to fix it also here:
https://github.com/MiT-HEP/NeroProducer/blob/master/Core/src/BareLeptons.cpp#L45
and here
https://github.com/MiT-HEP/NeroProducer/blob/master/Core/src/BareLeptons.cpp#L71

https://amarini.web.cern.ch/amarini/NeroProducer/7d5b22e29a257717f08dc3f23cbb180ebcee6592/run.txt

Since we didn't switch to this yet, I would also propose the following scheme for all the IDs, that we may use:
2^0               2^1        2^2          2^3        |  ---- 
VETO-ID LOOSE-ID MEDIUM  TIGHT   | NON POG ID

**Comment by yiiyama** [comment]
Oh crap, will do.

**Comment by drkovalskyi** [comment]
I think it's best to use a shift operation, not power. Here is what we used to have for event level selection for dilepton (just an example):
enum Selection {
    BaseLine           = 1UL<<0,  // pt(reco)>20/10, acceptance,!STA muon, mll>12                                                                                                                        
    ChargeMatch        = 1UL<<1,  // q1*q2<0                                                                                                                                                             
    Lep1FullSelection  = 1UL<<2,  // full id, isolation, d0, dz etc                                                                                                                                      
    Lep1LooseEleV1     = 1UL<<3,  // electron fakeable object selection is passed V1                                                                                                                     
    Lep1LooseEleV2     = 1UL<<4,  // electron fakeable object selection is passed V2                                                                                                                     
    Lep1LooseEleV3     = 1UL<<5,  // electron fakeable object selection is passed V3                                                                                                                     
    Lep1LooseEleV4     = 1UL<<6,  // electron fakeable object selection is passed V4                                                                                                                     
    Lep1LooseMuV1      = 1UL<<7,  // muon fakeable object selection (relIso<1.0)                                                                                                                         
    Lep1LooseMuV2      = 1UL<<8,  // muon fakeable object selection (relIso<0.4)                                                                                                                         
    Lep2FullSelection  = 1UL<<9,  // full id, isolation, d0, dz etc                                                                                                                                      
    Lep2LooseEleV1     = 1UL<<10, // electron fakeable object selection is passed V1                                                                                                                     
    Lep2LooseEleV2     = 1UL<<11, // electron fakeable object selection is passed V2                                                                                                                     
    Lep2LooseEleV3     = 1UL<<12, // electron fakeable object selection is passed V3                                                                                                                     
    Lep2LooseEleV4     = 1UL<<13, // electron fakeable object selection is passed V4                                                                                                                     
    Lep2LooseMuV1      = 1UL<<14, // muon fakeable object selection (relIso<1.0)                                                                                                                         
    Lep2LooseMuV2      = 1UL<<15, // muon fakeable object selection (relIso<0.4)                                                                                                                         
    FullMET            = 1UL<<16, // full met selection                                                                                                                                                  
    ZVeto              = 1UL<<17, // event is not in the Z-mass peak for ee/mm final states                                                                                                              
    TopTag             = 1UL<<18, // soft muon and b-jet tagging for the whole event regardless of n-jets (non-zero means tagged)                                                                        
    TopVeto            = 1UL<<19, // soft muon and b-jet tagging for the whole event regardless of n-jets (zero means tagged)                                                                            
    OneBJet            = 1UL<<20, // 1-jet events, where the jet is b-tagged (top control sample with one b-quark missing)                                                                               
    TopTagNotInJets    = 1UL<<21, // soft muon and b-jet tagging for areas outside primary jets (non-zero means tagged)                                                                                  
    ExtraLeptonVeto    = 1UL<<22, // extra lepton veto, DR(muon-electron)>=0.3                                                                                                                           
    Lep3FullSelection  = 1UL<<23,  // full id, isolation, d0, dz etc                                                                                                                                     
    Lep3LooseEleV1     = 1UL<<24, // electron fakeable object selection is passed V1                                                                                                                     
    Lep3LooseEleV2     = 1UL<<25, // electron fakeable object selection is passed V2                                                                                                                     
    Lep3LooseEleV3     = 1UL<<26, // electron fakeable object selection is passed V3                                                                                                                     
    Lep3LooseEleV4     = 1UL<<27, // electron fakeable object selection is passed V4                                                                                                                     
    Lep3LooseMuV1      = 1UL<<28, // muon fakeable object selection (relIso<1.0)                                                                                                                         
    Lep3LooseMuV2      = 1UL<<29, // muon fakeable object selection (relIso<0.4)                                                                                                                         
    Trigger            = 1UL<<30  // passed a set of triggers                                                                                                                                            
  };

**Comment by amarini** [comment]
Yes, the actual implementation is likely to be implemented using bitwise operation (shift, or, ..), the proposal was actually to try to unify the different ids, lepts, jets, taus, ... and try to converge to a pretty standard across the ntuples.

**Comment by amarini** [comment]
And to have a bit for the loose id, even if all the leptons should have it set, in such a way that if in the future we make it looser, code written on top may still work correctly.

**Comment by drkovalskyi** [comment]
That's not simple. Even standard ids are changing. We need a way to keep track of what "looseId" means. The id/iso framework from Lindsey will help with that.
Another complication is that we may have analysis specific selectors. So I would propose we reserve a few bits for standard selectors and use the rest at will. For example use the first 8 bits only for POG approved selectors and the rest can be anything and content makes sense only within a given analysis.

**Comment by amarini** [comment]
Yes, I perfectly agree with this statement. 

2^0 |  2^1  | 2^2 | 2^3 | ... | 2^8 | ...
----- | ------ | ----- | ----- | --- | ----- | ----
vetoPOG | loosePOG | mediumPOG | tightPOG | ... | MYID1 | ...

maybe an enum as you suggested will make the code more readable.

**Comment by yiiyama** [comment]
OK, seems settled then. I'll push the changes to this PR.

**Comment by yiiyama** [comment]
An enum and a passSelection() function were added to BareLeptons. NeroLeptons.cc is updated but only for medium and tight.

**Comment by amarini** [comment]
close #101

**Comment by yiiyama** [comment]
Since this PR touches Core and Nero I'm leaving it to @amarini et al to push the button.

**Comment by amarini** [comment]
ok. I'll merge it and open an issue to remind me to align the veto and loose bit.

**Pull request merged**
