### PR TITLE
CMSSW 80X 

### PR DESCRIPTION
**Pull request by amarini**
* small changes to make everything running on 80X
* otherthings may need extra checks. (GT for data, DB, Smearing/scale ...)

### CODE REVIEW

**Comment by zdemirag** [comment]
Will this be a separate branch? or did you tag the 76x?
I think we should have different working points (i.e. 74x branch, 76x branch etc)

**Comment by amarini** [comment]
yeah that's correct. do you prefer the master in 76X or in 8YX ? I will branch accordingly.

**Comment by amarini** [comment]
Updated to the master. Removed the recomputation of JEC and Met from GT, using the default in MiniAOD.

**Comment by yiiyama** [comment]
I went ahead and created a 76X branch - let me know if you guys were thinking otherwise.

**Comment by amarini** [comment]
+1
I think we should merge and make the master 80X.

**Pull request merged**
