### PR TITLE
Effective Area for electrons

### PR DESCRIPTION
**Pull request by amarini**
* effective area for electrons as default from Ilya.
* I'm trying to rederive the effective area subtractions and check dependence with charged iso and pt too.
* for the moment values are hard coded, need to think how to make them configurable with binnings, methods ...

### CODE REVIEW

**Comment by drkovalskyi** [comment]
Something is wrong with electron isolation. It's under correcting. Muon isolation is fine.

**Comment by drkovalskyi** [comment]
I found the problem. We need to use PF isolation, not the default isolation to get the recommended id:
https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_2/RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleEffAreaPFIsoCut.cc#L83-L94
I can make a pull request later today, but the fix is trivial. We still need to decide what we store in chIso and other components. I don't have a clear position myself.

**Comment by amarini** [comment]
maybe for consistency we switch to the pf isolation too. But I do not have a strong opinion.

**Comment by amarini** [comment]
I put as default the pf isolation for electrons. Need to be tested.

**Pull request merged**
