### PR TITLE
Topic 7 4 12

### PR DESCRIPTION
**Pull request by amarini**
Starting to collect the changes to run on 7_4_12 with "miniAODv2"

#119 

We need to discuss how to/if keep the branches for run on miniAODv2 and v1, accordingly to the plan to reminiAOD.

### CODE REVIEW

**Comment by amarini** [comment]
this [link](https://github.com/MiT-HEP/MCProduction#reminiaod) should be the instruction to reMiniAOD. (Not tested yet)

**Comment by amarini** [comment]
@zdemirag added the new egamma Id. (V1 for the moment). I'm checking the problem with the md5.

**Comment by amarini** [comment]
@zdemirag, the met updates in #126 have been implemented.
@yiiyama you may want at a certain point to integrate the puppiMet.

**Comment by yiiyama** [comment]
got it.

**Comment by amarini** [comment]
* Updated JEC. It happens that V5 and V2 are the default of miniAODv2. Not recomputing them. 
* Scripts have been update. 
* GT have been updated.
* close #122

**Comment by amarini** [comment]
@yiiyama, be aware of 5ecc3aa, I'll cherry pick on the master soon.

**Comment by yiiyama** [comment]
Thanks, good point. We won't start any production with the new format with selBits for another day or so.

**Comment by amarini** [comment]
I'm going to merge this today.

**Pull request merged**
