### PR TITLE
Factory

### PR DESCRIPTION
**Pull request by amarini**
* create a factory tool for the bare collection
* on top of PR #202

### CODE REVIEW

**Comment by drkovalskyi** [comment]
What is the reason for removing fatjets and reclustering? Also what is the Factory?

**Comment by amarini** [comment]
Hi, the possibility of switching on/off the reclustering have been introduced in #198, due to #194.

The Factory is a nice utility that allows you to create BareCollections from the name of the class (as string):

E.g.
~~~
    vector<string> classes {"BareEvent",                              
            "BareVertex",                                             
            "BareMonteCarlo",
            "BareJets",                                               
            "BareTaus",                                               
            "BareLeptons",
            "BareMet",
            "BareTrigger"
            };
vector<BareCollection*> bare_;
    for (const string & c : classes)                        
        bare_ . push_back( BareFactory::get().create( c ) ) ;         
~~~

It's a standard pattern in C++. Similar code is used for Plugins in CMSSW, ecc...
The basic idea is that you create a Singleton (only one instance of the class factory is allowed in the program), and there you register the method to construct the different classes (that can be easily templated).

It basically make the operation: new NAME, when you have NAME as a string.

**Comment by drkovalskyi** [comment]
Thanks for the clarification. So basically you just turned off reclustering, right?

**Comment by amarini** [comment]
As default, yes.

If you want, if you need, you can turn it on again.

Cheers,
-Andrea


Il 24.03.16 18:23, drkovalskyi ha scritto:
>
> Thanks for the clarification. So basically you just turned off
> reclustering, right?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/MiT-HEP/NeroProducer/pull/204#issuecomment-200936267>
>


-- 
Dr. Andrea Carlo Marini, 
c/o 32-4-A20 CERN

**Pull request merged**
