### PR TITLE
Tweaking the python configs to make them more subMIT-friendly

### PR DESCRIPTION
**Pull request by yiiyama**
Nothing changed for standard use.
Just had to move the part that uses subprocess git out of the cfi.
Added testNero_subMIT.py which executes testNero.py and changes some parameter values.

### CODE REVIEW

**Comment by yiiyama** [comment]
@amarini @demirag Nothing changed for standard use, but I'll wait for your approvals before merging.

**Comment by amarini** [comment]
For me it is fine. I made a small PR to this branch adapt as well the batch submission to the new format.

**Comment by demirag** [comment]
I have nothing to do with this project. I dont know why I am tagged :)

**Comment by yiiyama** [comment]
@demirag Ah sorry, wrong user tag.. Thanks for letting us know.

**Pull request merged**
